### ISSUE TITLE
Canvas no longer disabled when menu tray is engaged

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-iPad#4]
Prior to implementing autolayout, I believe that when the menu tray was exposed the app would lock the view that was pushed aside so that you couldn't interact with it (no scrolling, tapping on stories, etc.). This made the UX of closing the menu tray better because a user could swipe pretty much anywhere in order to close the menu. 

In the autolayout branch, the main view canvas remains fully interactive even when the menu tray is exposed. The preferred behavior would be to disable any interactions with the main view when the menu tray is engaged.

**Comment by bhawk9780** [comment]
Fixed for 1.0.7 build 2
