### ISSUE TITLE
Member sign-in view pushes off-canvas on orientation change

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-iPad#7]
Sequence:

* When signed out of the user profile, tap to sign in
* Tap the "Sign in as a Member" button
* Once the Member Sign-in screen loads, change the device orientation
* The form UI will move partially or entirely off-canvas when rotated

**Comment by bhawk9780** [comment]
Fixed for 1.0.7 build 2.

**Comment by bhawk9780** [comment]
Closing manually (bad commit message syntax)
